---
replicaCount: 1
image:
  registry: "ghcr.io"
  repository: "tkachovua/kbot"
  tag: "v1.0.2-72d0ccbad7ad364008a47ed4297048b8c16b07df"
  os: ""
  arch: ""
secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"
securityContext:
  privileged: true
