---
replicaCount: 1
image:
  registry: "ghcr.io"
  repository: "tkachovua/kbot"
  tag: "v1.0.2-6948f2d"
  os: ""
  arch: ""
secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"
securityContext:
  privileged: true
